### ISSUE TITLE
Readme a bit light

### ISSUE THREAD

**Issue by pach** [Augmenta-tech/Augmenta-Simulator_processing_legacy#1]
Readme looks to be a bit light.
Should at least tell which lib are necessary and links to download : 
g4p : gui for processing : http://www.lagers.org.uk/g4p/download.html
AugmentaP5 : https://github.com/Theoriz/AugmentaP5
OSCP5 : http://www.sojamo.de/libraries/oscP5/

Any I could have forgot?

**Comment by pach** [comment]
Ainsi qu'un lien vers le lien de dl des releases...
https://github.com/Theoriz/Augmenta-Simulator/releases

**Comment by Lyptik** [comment]
- Added Readme + instructions
- Added link to releases
- Added a thanks
- Added a new version
- Processing3 compatible

Thanks for pointing it out :)
