### ISSUE TITLE
nbPerson

### ISSUE THREAD

**Issue by pach** [Augmenta-tech/Augmenta-Simulator_processing_legacy#2]
Le nombre de personne renvoyé (/au/scene $2) semble etre toujours celui de la grille, qu'elle soit visible ou non, sans tenir compte de la personne "souris".
De meme, il semblerait que l'activité moyenne soit indépendant de la personne "souris".

**Comment by MatteoFantasy** [comment]
The number of people in the scene has been fixed, and the averageMotion and percentCovered are not implemented yet (replaced by random values with better documentation now)
