### ISSUE TITLE
Can't open Augmenta Simulator

### ISSUE THREAD

**Issue by kevinvennitti** [Augmenta-tech/Augmenta-Simulator_processing_legacy#3]
**OSX El Capitan**
[Installé de la dernière version pourtant](https://github.com/Theoriz/Augmenta-Simulator/releases/tag/V0_7)

_Note : le suffixe "3" est ajouté par Mac que parce que j'ai deux autres versions installées dans le même répertoire._

![28-03-2016 21 10 25 - finder](https://cloud.githubusercontent.com/assets/9624530/14087310/8fc4c9ea-f529-11e5-8940-4cd4c6907117.png)

**Comment by Lyptik** [comment]
On a eut des problèmes récemment avec la dernière version, je fait un réupload ce soir.

David C.
david.alexandre.chanel.ext@gmail.com

**Comment by Lyptik** [comment]
Reupload done, (généré depuis OSX 10.10.5 avec Processing 3.0.2) si tu as encore des problèmes, peux tu jeter un oeil au code pour nous donner une piste ? A bientôt

**Comment by Lyptik** [comment]
new update 0_7_2 on mac, might be ok :)

**Comment by kevinvennitti** [comment]
Avec la 0_7_2 :

![30-03-2016 09 56 08 - google chrome](https://cloud.githubusercontent.com/assets/9624530/14135423/a6eabdc0-f65d-11e5-8bc9-d3a161a3b9f6.png)

**Comment by Lyptik** [comment]
C’est très bizarre, c’est un binaire qui a été copié sur toutes nos machines, je vais tester si un téléchargement depuis Github crée ce genre de problème.

Pour faire un autre test, peux tu générer un binaire depuis ta machine et me l’envoyer ?

**Comment by kevinvennitti** [comment]
Ouvert avec Processing 2.2.1, après avoir installé la lib TUIO :

![30-03-2016 10 32 55 - processing](https://cloud.githubusercontent.com/assets/9624530/14136365/cefcfb5c-f662-11e5-830a-9a1ae449b651.png)

**Comment by Lyptik** [comment]
Le code est fonctionnel que sur Processing 3 il n’est plus maintenu Processing 2.

A savoir que sur certaine machine forcer le profil OpenGL ne marche pas (il est là uniquement pour Syphon), en revanche il n’y a pas de Syphon, es tu sur le dernier commit ?

Dans le dernier commit cette ligne est commentée.

**Comment by kevinvennitti** [comment]
Ok, avec le dernier commit, le Processing fonctionne. Je t'aurai bien filé la version exportée mais le bouton a disparu sous Processing 3 ?

**Comment by Lyptik** [comment]
Fichier -> exporter

**Comment by kevinvennitti** [comment]
Ok, le souci vient des autorisations à accorder aux softs non identifiés par les développeurs :

![30-03-2016 14 37 11 - google chrome](https://cloud.githubusercontent.com/assets/9624530/14142260/eff5a094-f684-11e5-985d-d109f17a8764.png)

Je ne serai donc pas le seul à avoir ce "souci" :
- S'identifier en tant que dev reconnu ?
- Préciser cette possibilité dans la Troubleshoot README

**Comment by Lyptik** [comment]
Ah ok, dans ce cas là il n’y a pas de problème, il faut effectivement mettre cette option si tu veux démarrer des programmes fait maison :)

C’est valable pour tout type de programme et même certain logiciel que tu peux télécharger sur le net.

Il y a peut-être des workaround que je ne connais pas pour authentifier.
